version: '3'
volumes:
    tomcat:
        external: false
    liberty:
        external: false
    nexus-works:
        external: false
services:
    jenkins:
        build: ./jenkins
        volumes:
            - .:/localdev
            - /var/run/docker.sock:/var/run/docker.sock
            - tomcat:/usr/share/jenkins/ref/tomcat
            - liberty:/usr/share/jenkins/ref/liberty
        environment:
            JAVA_OPTS: -Djenkins.install.runSetupWizard=false
        ports:
            - "18080:8080"
        depends_on:
            - dashboard
            - nexus
            - sonar
    nexus:
        image: sonatype/nexus
        volumes:
            - nexus-works:/sonatype-work
        ports:
            - "18081:8081"
    sonar:
        image: sonarqube
        ports:
            - "19000:9000"
    tomcat:
        image: tomcat
        ports:
            - "18888:8080"
        volumes:
            - tomcat:/usr/local/tomcat/webapps/
    liberty:
        image: websphere-liberty:webProfile7
        ports:
            - "9080:9080"
        volumes:
            - liberty:/config/dropins/
    dashboard:
        build: ./dashboard
        ports:
            - "80:80"
        healthcheck:
            test: curl -f http://dashboard
            interval: 15s
            timeout: 5s
            retries: 3
